# версия docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - "/app"
      - "/app:/storage"
    restart: always