# версия docker-compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  web:
    build: .
    restart: always
    # "зависит от", 
    env_file:
      - ./.env